# Pipeline to automatically mirror
# an Azure DevOps repository in a private GitHub repository

# Trigger on all branches
trigger:
- '*'

# Use latest Ubuntu image
pool:
  vmImage: 'ubuntu-latest'

# Pipeline
steps:
- checkout: none
- script: |
      # Install urlencode function to encode reserved characters in passwords
      sudo apt-get install gridsite-clients
      
      # Clone the repository
      git clone --branch $(Build.SourceBranchName) https://${AZURE_GIT_USERNAME}:$(urlencode ${AZURE_GIT_PASSWORD})@${AZURE_REPO_URL} repo-mirror
      
      # Sync GitHub repository
      cd repo-mirror
      
      # Fetch all branches from Azure
      git remote set-branches origin '*'
      git fetch origin --prune
      
      # Add GitHub remote
      git remote add github "https://${GITHUB_USERNAME}:$(urlencode ${GITHUB_TOKEN})@github.com/${GITHUB_USERNAME}/${GITHUB_REPO}.git"
      
      # Create local branches for all remote branches
      for branch in $(git branch -r | grep -v HEAD); do
          git branch --track "${branch#origin/}" "$branch"
      done
      
      # Push all local branches to GitHub
      git push github --all --force
      
  displayName: 'Sync repository with GitHub'
  env:
    AZURE_REPO_URL: $(AZURE_REPO_URL)
    AZURE_GIT_USERNAME: $(AZURE_GIT_USERNAME)
    AZURE_GIT_PASSWORD: $(AZURE_GIT_PASSWORD)
    GITHUB_USERNAME: $(GITHUB_USERNAME)
    GITHUB_TOKEN: $(GITHUB_TOKEN)
    GITHUB_REPO: $(GITHUB_REPO)