# Pipeline to automatically mirror
# an Azure DevOps repository in a private GitHub repository

# Trigger on specific branches
trigger:
- main
- Amplify

# Use latest Ubuntu image
pool:
  vmImage: 'ubuntu-latest'

# Pipeline
steps:
- checkout: none
- script: |
      # Install urlencode function to encode reserved characters in passwords
      sudo apt-get install gridsite-clients
      
      # Create local mirror of Azure DevOps repository
      git clone https://${AZURE_GIT_USERNAME}:$(urlencode ${AZURE_GIT_PASSWORD})@${AZURE_REPO_URL} repo-mirror
      
      # Change to repo directory
      cd repo-mirror
      
      # List all branches for debugging
      echo "Available branches:"
      git branch -a
      
      # Fetch specific branches
      git fetch origin main:refs/remotes/origin/main
      git fetch origin Amplify:refs/remotes/origin/Amplify
      
      # Create local branches
      git checkout -b main origin/main
      git checkout -b Amplify origin/Amplify
      
      # Add GitHub remote
      git remote add github "https://${GITHUB_USERNAME}:$(urlencode ${GITHUB_TOKEN})@github.com/${GITHUB_USERNAME}/${GITHUB_REPO}.git"
      
      # Push specific branches
      git push github main
      git push github Amplify
      
  displayName: 'Sync repository with GitHub'
  env:
    AZURE_REPO_URL: $(AZURE_REPO_URL)
    AZURE_GIT_USERNAME: $(AZURE_GIT_USERNAME)
    AZURE_GIT_PASSWORD: $(AZURE_GIT_PASSWORD)
    GITHUB_USERNAME: $(GITHUB_USERNAME)
    GITHUB_TOKEN: $(GITHUB_TOKEN)
    GITHUB_REPO: $(GITHUB_REPO)