# Pipeline to automatically mirror
# an Azure DevOps repository in a private GitHub repository

# Trigger on specific branches
trigger:
- main
- Amplify

# Use latest Ubuntu image
pool:
  vmImage: 'ubuntu-latest'

# Pipeline
steps:
- checkout: none
- script: |
      # Install urlencode function to encode reserved characters in passwords
      sudo apt-get install gridsite-clients
      
      # Create local mirror of Azure DevOps repository
      git clone --no-single-branch https://${AZURE_GIT_USERNAME}:$(urlencode ${AZURE_GIT_PASSWORD})@${AZURE_REPO_URL} repo-mirror
      
      # Sync GitHub repository
      cd repo-mirror
      
      # Add GitHub remote
      git remote add github "https://${GITHUB_USERNAME}:$(urlencode ${GITHUB_TOKEN})@github.com/${GITHUB_USERNAME}/${GITHUB_REPO}.git"
      
      # Fetch and push only main and Amplify branches
      git fetch origin main:main Amplify:Amplify
      git push github main Amplify --force
      
  displayName: 'Sync repository with GitHub'
  env:
    AZURE_REPO_URL: $(AZURE_REPO_URL)
    AZURE_GIT_USERNAME: $(AZURE_GIT_USERNAME)
    AZURE_GIT_PASSWORD: $(AZURE_GIT_PASSWORD)
    GITHUB_USERNAME: $(GITHUB_USERNAME)
    GITHUB_TOKEN: $(GITHUB_TOKEN)
    GITHUB_REPO: $(GITHUB_REPO)